<#ftl strip_whitespace=true strip_text=true />
<@cMacro name='cAccordion' group='components/accordion' />
<@cMacro name='cAlert' group='components/alert' />
<@cMacro name='cAnchor' group='components/anchor' />
<@cMacro name='cBadge' group='components/badge' />
<@cMacro name='cBtn' group='components/button' />
<@cMacro name='cBtnGroup' group='components/button' />
<@cMacro name='cBtnImg' group='components/button' />
<@cMacro name='cBtnToolbar' group='components/button' />
<@cMacro name='cCard' group='components/card' />
<@cMacro name='cCardFloating' group='components/card' />
<@cMacro name='cCardLayout' group='components/card' />
<@cMacro name='cCarousel' group='components/carousel' />
<@cMacro name='cCarouselItem' group='components/carousel' />
<@cMacro name='cCascading' group='components/cascading' />
<@cMacro name='cConsent' group='components/consent' />
<@cMacro name='getThemeDatePicker' group='components/datepicker' />
<@cMacro name='initThemeDatePicker' group='components/datepicker' />
<@cMacro name='cDropdown' group='components/dropdown' />
<@cMacro name='cErrorMessage' group='components/error' />
<@cMacro name='cFilter' group='components/filter' />
<@cMacro name='cIcon' group='components/icons' />
<@cMacro name='cList' group='components/list' />
<@cMacro name='cModal' group='components/modal' />
<@cMacro name='cOffcanvas' group='components/offcanvas' />
<@cMacro name='cPagination' group='components/pagination' />
<@cMacro name='cPaginationLinks' group='components/pagination' />
<@cMacro name='cProgress' group='components/progress' />
<@cMacro name='cSearchSetResultPageTitle' group='components/search' />
<@cMacro name='cScrollSpy' group='components/scrollspy' />
<@cMacro name='cSkeleton' group='components/skeleton' />
<@cMacro name='cInfoStep' group='components/stepinfo' />
<@cMacro name='cSlider' group='components/slider' />
<@cMacro name='cStepper' group='components/stepper' />
<@cMacro name='cStatus' group='components/status' />
<@cMacro name='cTab' group='components/tabs' />
<@cMacro name='cTabContent' group='components/tabs' />
<@cMacro name='cTabPane' group='components/tabs' />
<@cMacro name='cTabs' group='components/tabs' />
<@cMacro name='cTheme' group='components/theme' />
<@cMacro name='cContentFrame' group='components/text' />
<@cMacro name='cDivider' group='components/text' />
<@cMacro name='cSetPageTitle' group='components/title' />
<@cMacro name='cArticle' group='elements/article' />
<@cMacro name='cFooter' group='elements/footer' />
<@cMacro name='cHeader' group='elements/header' />
<@cMacro name='cFigCaption' group='elements/images' />
<@cMacro name='cFigure' group='elements/images' />
<@cMacro name='cImg' group='elements/images' />
<@cMacro name='cPicture' group='elements/images' />
<@cMacro name='cPictureSrc' group='elements/images' />
<@cMacro name='cLink' group='elements/link' />
<@cMacro name='chItem' group='elements/list' />
<@cMacro name='chList' group='elements/list' />
<@cMacro name='cBlock' group='elements/section' />
<@cMacro name='cSection' group='elements/section' />
<@cMacro name='cTable' group='elements/table' />
<@cMacro name='cTbody' group='elements/table' />
<@cMacro name='cTd' group='elements/table' />
<@cMacro name='cTfoot' group='elements/table' />
<@cMacro name='cTh' group='elements/table' />
<@cMacro name='cThead' group='elements/table' />
<@cMacro name='cTr' group='elements/table' />
<@cMacro name='cInline' group='elements/text' />
<@cMacro name='cText' group='elements/text' />
<@cMacro name='cTitle' group='elements/title' />
<@cMacro name='cFormCheck' group='forms/check_radio' />
<@cMacro name='cCheckbox' group='forms/check_radio' />
<@cMacro name='cRadio' group='forms/check_radio' />
<@cMacro name='cInputGroup' group='forms/inputgroup' />
<@cMacro name='cInputGroupAddon' group='forms/inputgroup' />
<@cMacro name='cInputGroupAddonText' group='forms/inputgroup' />
<@cMacro name='cField' group='forms/inputs' />
<@cMacro name='cFormHelp' group='forms/inputs' />
<@cMacro name='cInput' group='forms/inputs' />
<@cMacro name='cInputDate' group='forms/inputs' />
<@cMacro name='cInputPassword' group='forms/inputs' />
<@cMacro name='cInputTimeSlot' group='forms/inputs' />
<@cMacro name='cPasswordMeter' group='forms/inputs' />
<@cMacro name='cQuantityPicker' group='forms/inputs' />
<@cMacro name='cLabel' group='forms/inputs' />
<@cMacro name='cTextArea' group='forms/inputs' />
<@cMacro name='cFieldset' group='forms/layout' />
<@cMacro name='cForm' group='forms/layout' />
<@cMacro name='cFormRow' group='forms/layout' />
<@cMacro name='cMultiselect' group='forms/multiselect' />
<@cMacro name='cMultiselectOption' group='forms/multiselect' />
<@cMacro name='cOptgroup' group='forms/select' />
<@cMacro name='cOption' group='forms/select' />
<@cMacro name='cSelect' group='forms/select' />
<@cMacro name='cStepContent' group='forms/steps' />
<@cMacro name='cStepCurrent' group='forms/steps' />
<@cMacro name='cStepDone' group='forms/steps' />
<@cMacro name='cStepGroup' group='forms/steps' />
<@cMacro name='cStepNext' group='forms/steps' />
<@cMacro name='cInputDropFiles' group='forms/upload' />
<@cMacro name='cInputDropFilesItem' group='forms/upload' />
<@cMacro name='cFormError' group='forms/validation' />
<@cMacro name='cPasswordCheck' group='forms/validation' />
<@cMacro name='cMainBanner' group='layout/banner' />
<@cMacro name='cBreadCrumb' group='layout/breadcrumb' />
<@cMacro name='cDropNav' group='layout/navigation' />
<@cMacro name='cMainNav' group='layout/navigation' />
<@cMacro name='cMainNavItem' group='layout/navigation' />
<@cMacro name='cMainNavUser' group='layout/navigation' />
<@cMacro name='skipNav' group='layout/navigation' />
<@cMacro name='goToTop' group='layout/navigation' />
<@cMacro name='cMainFooter' group='layout/footer' />
<@cMacro name='cMainFooterSocial' group='layout/footer' />
<@cMacro name='_footerMenu' group='layout/footer' />
<@cMacro name='cCol' group='layout/layout' />
<@cMacro name='cContainer' group='layout/layout' />
<@cMacro name='cRow' group='layout/layout' />
<@cMacro name='charCounter' group='components/javascript' />
<@cMacro name='codeHighLight' group='components/javascript' />
<@cMacro name='copyElementToClipboard' group='components/javascript' />
<@cMacro name='cSessionTimeout' group='components/javascript' />
<@cMacro name='scrollTopBtn' group='components/javascript' />
<@cMacro name='cToast' group='components/javascript' />
<@cMacro name='deprecatedWarning' group='utilities/functions'  />
<@cMacro name='rand' group='utilities/functions'  />    