<#ftl strip_whitespace=true strip_text=true />
<#-- DO NOT UPDATE                            -->
<#include "${commonsMacrosPath}components/accordion/cAccordion.ftl" />
<#include "${commonsMacrosPath}components/cascading/cCascading.ftl" />
<#include "${commonsMacrosPath}components/alert/cAlert.ftl" />
<#include "${commonsMacrosPath}components/anchor/cAnchor.ftl" />
<#include "${commonsMacrosPath}components/badge/cBadge.ftl" />
<#include "${commonsMacrosPath}components/button/cBtn.ftl" />
<#include "${commonsMacrosPath}components/button/cBtnGroup.ftl" />
<#include "${commonsMacrosPath}components/button/cBtnImg.ftl" />
<#include "${commonsMacrosPath}components/button/cBtnToolbar.ftl" />
<#include "${commonsMacrosPath}components/card/cCard.ftl" />
<#include "${commonsMacrosPath}components/card/cCardFloating.ftl" />
<#include "${commonsMacrosPath}components/card/cCardLayout.ftl" />
<#include "${commonsMacrosPath}components/carousel/cCarousel.ftl" />
<#include "${commonsMacrosPath}components/carousel/cCarouselItem.ftl" />
<#include "${commonsMacrosPath}components/consent/cConsentTac.ftl" />
<#include "${commonsMacrosPath}components/consent/cConsentTacService.ftl" />
<#include "${commonsMacrosPath}components/consent/cConsentTacServiceMatomo.ftl" />
<#include "${commonsMacrosPath}components/datepicker/getThemeDatePicker.ftl" />
<#include "${commonsMacrosPath}components/datepicker/initThemeDatePicker.ftl" />
<#include "${commonsMacrosPath}components/error/cErrorMessage.ftl" />
<#include "${commonsMacrosPath}components/filter/cFilter.ftl" />
<#include "${commonsMacrosPath}components/icons/cIcon.ftl" />
<#include "${commonsMacrosPath}components/icons/parisIcon.ftl" />
<#include "${commonsMacrosPath}components/icons/parisIconPack.ftl" />
<#include "${commonsMacrosPath}components/icons/logoParisService.ftl" />
<#include "${commonsMacrosPath}components/javascript/charCounter.ftl" />
<#include "${commonsMacrosPath}components/javascript/codeHighLight.ftl" />
<#include "${commonsMacrosPath}components/javascript/copyElementToClipboard.ftl" />
<#include "${commonsMacrosPath}components/javascript/scrollTopBtn.ftl" />
<#include "${commonsMacrosPath}components/javascript/cToast.ftl" />
<#include "${commonsMacrosPath}components/franceconnect/fcBtnImg.ftl" />
<#include "${commonsMacrosPath}components/franceconnect/fcImg.ftl" />
<#include "${commonsMacrosPath}components/franceconnect/fcMessage.ftl" />
<#include "${commonsMacrosPath}components/list/cCustomList.ftl" />
<#include "${commonsMacrosPath}components/list/cCustomListArrow.ftl" />
<#include "${commonsMacrosPath}components/list/cList.ftl" />
<#include "${commonsMacrosPath}components/modal/cModal.ftl" />
<#include "${commonsMacrosPath}components/offcanvas/cOffcanvas.ftl" />
<#include "${commonsMacrosPath}components/pagination/cPagination.ftl" />
<#include "${commonsMacrosPath}components/pagination/cPaginationLinks.ftl" />
<#include "${commonsMacrosPath}components/progress/cProgress.ftl" />
<#include "${commonsMacrosPath}components/search/cSearchSetResultPageTitle.ftl" />
<#include "${commonsMacrosPath}components/stepinfo/cInfoStep.ftl" />
<#include "${commonsMacrosPath}components/slider/cSlider.ftl" />
<#include "${commonsMacrosPath}components/stepinfo/cStepper.ftl" />
<#include "${commonsMacrosPath}components/status/cStatus.ftl" />
<#include "${commonsMacrosPath}components/tabs/cTab.ftl" />
<#include "${commonsMacrosPath}components/tabs/cTabContent.ftl" />
<#include "${commonsMacrosPath}components/tabs/cTabPane.ftl" />
<#include "${commonsMacrosPath}components/tabs/cTabs.ftl" />
<#include "${commonsMacrosPath}components/theme/cTheme.ftl" />
<#include "${commonsMacrosPath}components/text/cContentFrame.ftl" />
<#include "${commonsMacrosPath}components/text/cDivider.ftl" />
<#include "${commonsMacrosPath}components/title/cSetPageTitle.ftl" />
<#include "${commonsMacrosPath}elements/article/cArticle.ftl" />
<#include "${commonsMacrosPath}elements/footer/cFooter.ftl" />
<#include "${commonsMacrosPath}elements/header/cHeader.ftl" />
<#include "${commonsMacrosPath}elements/images/cFigCaption.ftl" />
<#include "${commonsMacrosPath}elements/images/cFigure.ftl" />
<#include "${commonsMacrosPath}elements/images/cImg.ftl" />
<#include "${commonsMacrosPath}elements/images/cPicture.ftl" />
<#include "${commonsMacrosPath}elements/images/cPictureSrc.ftl" />
<#include "${commonsMacrosPath}elements/link/cLink.ftl" />
<#include "${commonsMacrosPath}elements/list/chItem.ftl" />
<#include "${commonsMacrosPath}elements/list/chList.ftl" />
<#include "${commonsMacrosPath}elements/section/cBlock.ftl" />
<#include "${commonsMacrosPath}elements/section/cSection.ftl" />
<#include "${commonsMacrosPath}elements/table/cTable.ftl" />
<#include "${commonsMacrosPath}elements/table/cTbody.ftl" />
<#include "${commonsMacrosPath}elements/table/cTd.ftl" />
<#include "${commonsMacrosPath}elements/table/cTfoot.ftl" />
<#include "${commonsMacrosPath}elements/table/cTh.ftl" />
<#include "${commonsMacrosPath}elements/table/cThead.ftl" />
<#include "${commonsMacrosPath}elements/table/cTr.ftl" />
<#include "${commonsMacrosPath}elements/text/cInline.ftl" />
<#include "${commonsMacrosPath}elements/text/cText.ftl" />
<#include "${commonsMacrosPath}elements/title/cTitle.ftl" />
<#include "${commonsMacrosPath}forms/check_radio/cFormCheck.ftl" />
<#include "${commonsMacrosPath}forms/check_radio/cCheckbox.ftl" />
<#include "${commonsMacrosPath}forms/check_radio/cRadio.ftl" />
<#include "${commonsMacrosPath}forms/inputgroup/cInputGroup.ftl" />
<#include "${commonsMacrosPath}forms/inputgroup/cInputGroupAddon.ftl" />
<#include "${commonsMacrosPath}forms/inputgroup/cInputGroupAddonText.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cField.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cFormHelp.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cInput.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cInputDate.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cInputPassword.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cPasswordMeter.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cQuantityPicker.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cLabel.ftl" />
<#include "${commonsMacrosPath}forms/inputs/cTextArea.ftl" />
<#include "${commonsMacrosPath}forms/layout/cFieldset.ftl" />
<#include "${commonsMacrosPath}forms/layout/cForm.ftl" />
<#include "${commonsMacrosPath}forms/layout/cFormRow.ftl" />
<#include "${commonsMacrosPath}forms/multiselect/cMultiselect.ftl" />
<#include "${commonsMacrosPath}forms/multiselect/cMultiselectOption.ftl" />
<#include "${commonsMacrosPath}forms/select/cOptgroup.ftl" />
<#include "${commonsMacrosPath}forms/select/cOption.ftl" />
<#include "${commonsMacrosPath}forms/select/cSelect.ftl" />
<#include "${commonsMacrosPath}forms/steps/cStepContent.ftl" />
<#include "${commonsMacrosPath}forms/steps/cStepCurrent.ftl" />
<#include "${commonsMacrosPath}forms/steps/cStepDone.ftl" />
<#include "${commonsMacrosPath}forms/steps/cStepGroup.ftl" />
<#include "${commonsMacrosPath}forms/steps/cStepNext.ftl" />
<#include "${commonsMacrosPath}forms/upload/cInputDropFiles.ftl" />
<#include "${commonsMacrosPath}forms/upload/cInputDropFilesItem.ftl" />
<#include "${commonsMacrosPath}forms/validation/cFormError.ftl" />
<#include "${commonsMacrosPath}forms/validation/cPasswordCheck.ftl/" />
<#include "${commonsMacrosPath}layout/banner/cMainBanner.ftl" />
<#include "${commonsMacrosPath}layout/breadcrumb/cBreadCrumb.ftl" />
<#include "${commonsMacrosPath}layout/navigation/cDropNav.ftl" />
<#include "${commonsMacrosPath}layout/navigation/cMainNav.ftl" />
<#include "${commonsMacrosPath}layout/navigation/cMainNavItem.ftl" />
<#include "${commonsMacrosPath}layout/navigation/cMainNavUser.ftl" />
<#include "${commonsMacrosPath}layout/navigation/skipNav.ftl" />
<#include "${commonsMacrosPath}layout/navigation/goToTop.ftl" />
<#include "${commonsMacrosPath}layout/footer/cMainFooter.ftl" />
<#include "${commonsMacrosPath}layout/footer/_footerMenu.ftl" />
<#include "${commonsMacrosPath}layout/layout/cCol.ftl" />
<#include "${commonsMacrosPath}layout/layout/cContainer.ftl" />
<#include "${commonsMacrosPath}layout/layout/cRow.ftl" />
<#include "${commonsMacrosPath}utilities/functions/deprecatedWarning.ftl" />
<#include "${commonsMacrosPath}utilities/functions/rand.ftl" />