ALTER TABLE core_page ADD COLUMN workgroup_key varchar(50) DEFAULT NULL;

ALTER TABLE core_page ADD COLUMN workgroup_key varchar(50) collate utf8_unicode_ci DEFAULT NULL;

DROP TABLE IF EXISTS core_portlet_type;

CREATE TABLE core_portlet_type (
  id_portlet_type varchar(50) collate utf8_unicode_ci NOT NULL default '0',
  name varchar(255) collate utf8_unicode_ci default NULL,
  url_creation varchar(255) collate utf8_unicode_ci default NULL,
  url_update varchar(255) collate utf8_unicode_ci default NULL,
  home_class varchar(255) collate utf8_unicode_ci default NULL,
  plugin_name varchar(50) collate utf8_unicode_ci default NULL,
  url_docreate varchar(255) collate utf8_unicode_ci default NULL,
  create_script varchar(255) collate utf8_unicode_ci default NULL,
  create_specific varchar(255) collate utf8_unicode_ci default NULL,
  create_specific_form varchar(255) collate utf8_unicode_ci default NULL,
  url_domodify varchar(255) collate utf8_unicode_ci default NULL,
  modify_script varchar(255) collate utf8_unicode_ci default NULL,
  modify_specific varchar(255) collate utf8_unicode_ci default NULL,
  modify_specific_form varchar(255) collate utf8_unicode_ci default NULL,
  PRIMARY KEY  (id_portlet_type)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into core_portlet_type(id_portlet_type,name,url_creation,url_update,home_class,plugin_name,url_docreate,create_script,create_specific,create_specific_form,url_domodify,modify_script,modify_specific,modify_specific_form) values ('ALIAS_PORTLET','portal.site.portletAlias.name','plugins/alias/CreatePortletAlias.jsp','plugins/alias/ModifyPortletAlias.jsp','fr.paris.lutece.portal.business.portlet.AliasPortletHome','alias','plugins/alias/DoCreatePortletAlias.jsp','/admin/portlet/script_create_portlet.html','/admin/portlet/alias/create_portlet_alias.html','','plugins/alias/DoModifyPortletAlias.jsp','/admin/portlet/script_modify_portlet.html','/admin/portlet/alias/modify_portlet_alias.html','');
-- ,
-- ('CALENDAR_PORTLET','calendar.portlet.name','plugins/calendar/CreatePortletCalendar.jsp','plugins/calendar/ModifyPortletCalendar.jsp','fr.paris.lutece.plugins.calendar.business.portlet.CalendarPortletHome','calendar','plugins/calendar/DoCreatePortletCalendar.jsp','/admin/portlet/script_create_portlet.html','','','plugins/calendar/DoModifyPortletCalendar.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/calendar/portlet_modify_calendar.html',''),
-- ('CHILDPAGES_PORTLET','childpages.portlet.name','plugins/childpages/CreatePortletChildPages.jsp','plugins/childpages/ModifyPortletChildPages.jsp','fr.paris.lutece.plugins.childpages.business.portlet.ChildPagesPortletHome','childpages','plugins/childpages/DoCreatePortletChildPages.jsp','/admin/portlet/script_create_portlet.html','/admin/plugins/childpages/value_id_parent.html','','plugins/childpages/DoModifyPortletChildPages.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/childpages/value_id_parent.html',''),('DBPAGE_PORTLET','dbpage.portlet.name','plugins/dbpage/CreatePortletDbPage.jsp','plugins/dbpage/ModifyPortletDbPage.jsp','fr.paris.lutece.plugins.dbpage.business.portlet.DbPagePortletHome','dbpage','plugins/dbpage/DoCreatePortletDbPage.jsp','/admin/portlet/script_create_portlet.html','/admin/plugins/dbpage/portlet/portlet_dbpage_type.html','','plugins/dbpage/DoModifyPortletDbPage.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/dbpage/portlet/portlet_dbpage_type.html',''),
-- ('DOCUMENT_LIST_PORTLET','document.portlet.documentListPortlet.name','plugins/document/CreateDocumentListPortlet.jsp','plugins/document/ModifyDocumentListPortlet.jsp','fr.paris.lutece.plugins.document.business.portlet.DocumentListPortletHome','document','plugins/document/DoCreateDocumentListPortlet.jsp','/admin/portlet/script_create_portlet.html','/admin/plugins/document/portlet/document_list_portlet_type.html','','plugins/document/DoModifyDocumentListPortlet.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/document/portlet/document_list_portlet_type.html',''),
-- ('DOCUMENT_PORTLET','document.portlet.documentPortlet.name','plugins/document/CreateDocumentPortlet.jsp','plugins/document/ModifyDocumentPortlet.jsp','fr.paris.lutece.plugins.document.business.portlet.DocumentPortletHome','document','plugins/document/DoCreateDocumentPortlet.jsp','/admin/portlet/script_create_portlet.html','/admin/plugins/document/portlet/document_portlet_type.html','','plugins/document/DoModifyDocumentPortlet.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/document/portlet/document_portlet_type.html',''),
-- ('HTML_PORTLET','html.portlet.name','plugins/html/CreatePortletHtml.jsp','plugins/html/ModifyPortletHtml.jsp','fr.paris.lutece.plugins.html.business.portlet.HtmlPortletHome','html','plugins/html/DoCreatePortletHtml.jsp','/admin/portlet/script_create_portlet.html','/admin/plugins/html/portlet_html.html','','plugins/html/DoModifyPortletHtml.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/html/portlet_html.html',''),
-- ('LINK_PAGES_PORTLET','linkpages.portlet.name','plugins/linkpages/CreatePortletLinkPages.jsp','plugins/linkpages/ModifyPortletLinkPages.jsp','fr.paris.lutece.plugins.linkpages.business.portlet.LinkPagesPortletHome','linkpages','plugins/linkpages/DoCreatePortletLinkPages.jsp','/admin/portlet/script_create_portlet.html','','','plugins/linkpages/DoModifyPortletLinkPages.jsp','/admin/portlet/script_modify_portlet.html','','/admin/plugins/linkpages/modify_portlet_linkpages_list.html'),
-- ('MYLUTECE_PORTLET','mylutece.portlet.name','plugins/mylutece/CreatePortletMyLutece.jsp','plugins/mylutece/ModifyPortletMyLutece.jsp','fr.paris.lutece.plugins.mylutece.business.portlet.MyLutecePortletHome','mylutece','plugins/mylutece/DoCreatePortletMyLutece.jsp','/admin/portlet/script_create_portlet.html','','','plugins/mylutece/DoModifyPortletMyLutece.jsp','/admin/portlet/script_modify_portlet.html','',''),
-- ('NEWSLETTER_ARCHIVE_PORTLET','newsletter.portlet.name','plugins/newsletter/CreatePortletNewsletter.jsp','plugins/newsletter/ModifyPortletNewsletter.jsp','fr.paris.lutece.plugins.newsletter.business.portlet.NewsLetterArchivePortletHome','newsletter','plugins/newsletter/DoCreatePortletNewsletter.jsp','/admin/portlet/script_create_portlet.html','','','plugins/newsletter/DoModifyPortletNewsletter.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/newsletter/newsletter_sending_list.html',''),
-- ('NEWSLETTER_SUBSCRIPTION_PORTLET','newsletter.portlet.subscription.name','plugins/newsletter/CreateSubscriptionPortletNewsletter.jsp','plugins/newsletter/ModifySubscriptionPortletNewsletter.jsp','fr.paris.lutece.plugins.newsletter.business.portlet.NewsLetterSubscriptionPortletHome','newsletter','plugins/newsletter/DoCreateSubscriptionPortletNewsletter.jsp','/admin/portlet/script_create_portlet.html','','','plugins/newsletter/DoModifySubscriptionPortletNewsletter.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/newsletter/newsletter_subscription_list.html',''),
-- ('QUICKLINKS_PORTLET','quicklinks.portlet.name','plugins/quicklinks/CreateQuicklinksPortlet.jsp','plugins/quicklinks/ModifyQuicklinksPortlet.jsp','fr.paris.lutece.plugins.quicklinks.business.portlet.QuicklinksPortletHome','quicklinks','plugins/quicklinks/DoCreateQuicklinksPortlet.jsp','','/admin/plugins/quicklinks/list_quicklinks.html','','plugins/quicklinks/DoModifyQuicklinksPortlet.jsp','','/admin/plugins/quicklinks/list_quicklinks.html',''),
-- ('RSS_PORTLET','rss.portlet.name','plugins/rss/CreatePortletRss.jsp','plugins/rss/ModifyPortletRss.jsp','fr.paris.lutece.plugins.rss.business.portlet.RssPortletHome','rss','plugins/rss/DoCreatePortletRss.jsp','/admin/portlet/script_create_portlet.html','/admin/plugins/rss/portlet/create_portlet_rss.html','','plugins/rss/DoModifyPortletRss.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/rss/portlet/modify_portlet_rss.html',''),
-- ('WHATS_NEW_PORTLET','whatsnew.portlet.name','plugins/whatsnew/CreatePortletWhatsNew.jsp','plugins/whatsnew/ModifyPortletWhatsNew.jsp','fr.paris.lutece.plugins.whatsnew.business.portlet.WhatsNewPortletHome','whatsnew','plugins/whatsnew/DoCreatePortletWhatsNew.jsp','/admin/portlet/script_create_portlet.html','/admin/plugins/whatsnew/create_portlet_whatsnew.html','','plugins/whatsnew/DoModifyPortletWhatsNew.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/whatsnew/modify_portlet_whatsnew.html',''),
-- ('XMLPAGE_PORTLET','xmlpage.portlet.name','plugins/xmlpage/CreatePortletXmlPage.jsp','plugins/xmlpage/ModifyPortletXmlPage.jsp','fr.paris.lutece.plugins.xmlpage.business.portlet.XmlPagePortletHome','xmlpage','plugins/xmlpage/DoCreatePortletXmlPage.jsp','/admin/portlet/script_create_portlet.html','/admin/plugins/xmlpage/create_portlet_xmlpage.html','','plugins/xmlpage/DoModifyPortletXmlPage.jsp','/admin/portlet/script_modify_portlet.html','/admin/plugins/xmlpage/modify_portlet_xmlpage.html','');

