--liquibase formatted sql
--changeset core:update_db_lutece_core-7.1.x-8.0.0.sql
--preconditions onFail:MARK_RAN onError:WARN
ALTER TABLE core_level_right ALTER COLUMN id_level DROP DEFAULT;
DROP TABLE IF EXISTS core_mode;

DROP TABLE IF EXISTS core_theme_global;

--
-- Update core_theme datas
--
DROP TABLE IF EXISTS core_theme;
CREATE TABLE IF NOT EXISTS core_theme (
  code_theme varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  theme_description varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  path_images varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  path_css varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  theme_author varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  theme_author_url varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  theme_version varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  theme_licence varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  path_js varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (code_theme)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DELETE FROM core_theme;

INSERT INTO core_theme (code_theme, theme_description, path_images, path_css, theme_author, theme_author_url, theme_version, theme_licence, path_js) VALUES ('lutece', 'Lutece', 'images/', 'css', 'Ville de Paris', 'https://lutece.paris.fr', '1.0', 'BSD', 'js');

--
-- Update core_datastore keys
--
DELETE FROM core_datastore WHERE entity_key='core_banned_domain_names';
INSERT INTO core_datastore VALUES ('core_banned_domain_names', 'yopmail.com');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.access_failures_captcha';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.access_failures_captcha', '1');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.access_failures_interval';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.access_failures_interval', '10');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.access_failures_max';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.access_failures_max', '3');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.account_life_time';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.account_life_time', '12');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.account_reactivated_mail_sender';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.account_reactivated_mail_sender', 'lutece@nowhere.com');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.account_reactivated_mail_subject';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.account_reactivated_mail_subject', 'Votre compte a bien été réactivé');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.default_user_language';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.default_user_language', 'fr');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.default_user_level';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.default_user_level', '0');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.default_user_notification';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.default_user_notification', '1');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.default_user_status';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.default_user_status', '0');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.email_pattern';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.email_pattern', '^[\\w_.\\-!\\#$\\%\\&\'\\*\\+\\/\\=\\?\\^\\\\}\\{\\|\\~]+@[\\w_.\\-]+\\.[\\w]+$');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.email_pattern_verify_by';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.email_pattern_verify_by', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.expired_alert_mail_sender';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.expired_alert_mail_sender', 'lutece@nowhere.com');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.expired_alert_mail_subject';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.expired_alert_mail_subject', 'Votre compte a expiré');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.first_alert_mail_sender';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.first_alert_mail_sender', 'lutece@nowhere.com');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.first_alert_mail_subject';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.first_alert_mail_subject', 'Votre compte va bientôt expirer');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.force_change_password_reinit';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.force_change_password_reinit', 'true');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.lock_reset_token_to_session';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.lock_reset_token_to_session', 'false');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.maximum_number_password_change';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.maximum_number_password_change', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.nb_alert_account';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.nb_alert_account', '2');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.notify_user_password_expired';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.notify_user_password_expired', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.other_alert_mail_sender';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.other_alert_mail_sender', 'lutece@nowhere.com');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.other_alert_mail_subject';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.other_alert_mail_subject', 'Votre compte va bientôt expirer');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.password_duration';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.password_duration', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.password_expired_mail_sender';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.password_expired_mail_sender', 'lutece@nowhere.com');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.password_expired_mail_subject';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.password_expired_mail_subject', 'Votre mot de passe a expiré');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.password_format_numero';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.password_format_numero', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.password_format_special_characters';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.password_format_special_characters', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.password_format_upper_lower_case';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.password_format_upper_lower_case', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.password_history_size';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.password_history_size', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.password_minimum_length';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.password_minimum_length', '8');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.reset_token_validity';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.reset_token_validity', '60');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.time_before_alert_account';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.time_before_alert_account', '30');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.time_between_alerts_account';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.time_between_alerts_account', '10');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.tsw_size_password_change';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.tsw_size_password_change', '');
DELETE FROM core_datastore WHERE entity_key='core.advanced_parameters.use_advanced_security_parameters';
INSERT INTO core_datastore VALUES ('core.advanced_parameters.use_advanced_security_parameters', '');
DELETE FROM core_datastore WHERE entity_key='core.backOffice.defaultEditor';
INSERT INTO core_datastore VALUES ('core.backOffice.defaultEditor', 'tinymce6');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.BaseUserPreferencesCacheService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.BaseUserPreferencesCacheService.enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.BaseUserPreferencesCacheService.maxElementsInMemory';
INSERT INTO core_datastore VALUES ('core.cache.status.BaseUserPreferencesCacheService.maxElementsInMemory', '1000');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.DatastoreCacheService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.DatastoreCacheService.enabled', '1');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.LinksIncludeCacheService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.LinksIncludeCacheService.enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.LuteceUserCacheService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.LuteceUserCacheService.enabled', '1');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.LuteceUserCacheService.maxElementsInMemory';
INSERT INTO core_datastore VALUES ('core.cache.status.LuteceUserCacheService.maxElementsInMemory', '1000');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.MailAttachmentCacheService.diskPersistent';
INSERT INTO core_datastore VALUES ('core.cache.status.MailAttachmentCacheService.diskPersistent', 'true');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.MailAttachmentCacheService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.MailAttachmentCacheService.enabled', '1');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.MailAttachmentCacheService.maxElementsInMemory';
INSERT INTO core_datastore VALUES ('core.cache.status.MailAttachmentCacheService.maxElementsInMemory', '10');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.MailAttachmentCacheService.overflowToDisk';
INSERT INTO core_datastore VALUES ('core.cache.status.MailAttachmentCacheService.overflowToDisk', 'true');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.MailAttachmentCacheService.timeToLiveSeconds';
INSERT INTO core_datastore VALUES ('core.cache.status.MailAttachmentCacheService.timeToLiveSeconds', '7200');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.MyPortalWidgetContentService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.MyPortalWidgetContentService.enabled', '1');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.MyPortalWidgetService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.MyPortalWidgetService.enabled', '1');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.PageCacheService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.PageCacheService.enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.PageCachingFilter.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.PageCachingFilter.enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.PageCachingFilter(CAUTION:NEVERUSEWITHUSERDYNAMICDATA).enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.PageCachingFilter(CAUTION:NEVERUSEWITHUSERDYNAMICDATA).enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.pathCacheService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.pathCacheService.enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.PortalMenuService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.PortalMenuService.enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.PortletCacheService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.PortletCacheService.enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.SiteMapService.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.SiteMapService.enabled', '1');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.StaticFilesCachingFilter.enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.StaticFilesCachingFilter.enabled', '0');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.StaticFilesCachingFilter.timeToLiveSeconds';
INSERT INTO core_datastore VALUES ('core.cache.status.StaticFilesCachingFilter.timeToLiveSeconds', '604800');
DELETE FROM core_datastore WHERE entity_key='core.cache.status.XMLTransformerCacheService(XSLT).enabled';
INSERT INTO core_datastore VALUES ('core.cache.status.XMLTransformerCacheService(XSLT).enabled', '1');
DELETE FROM core_datastore WHERE entity_key='core.daemon.accountLifeTimeDaemon.interval';
INSERT INTO core_datastore VALUES ('core.daemon.accountLifeTimeDaemon.interval', '86400');
DELETE FROM core_datastore WHERE entity_key='core.daemon.accountLifeTimeDaemon.onStartUp';
INSERT INTO core_datastore VALUES ('core.daemon.accountLifeTimeDaemon.onStartUp', 'true');
DELETE FROM core_datastore WHERE entity_key='core.daemon.anonymizationDaemon.interval';
INSERT INTO core_datastore VALUES ('core.daemon.anonymizationDaemon.interval', '86400');
DELETE FROM core_datastore WHERE entity_key='core.daemon.anonymizationDaemon.onStartUp';
INSERT INTO core_datastore VALUES ('core.daemon.anonymizationDaemon.onStartUp', 'false');
DELETE FROM core_datastore WHERE entity_key='core.daemon.indexer.interval';
INSERT INTO core_datastore VALUES ('core.daemon.indexer.interval', '300');
DELETE FROM core_datastore WHERE entity_key='core.daemon.indexer.onStartUp';
INSERT INTO core_datastore VALUES ('core.daemon.indexer.onStartUp', 'true');
DELETE FROM core_datastore WHERE entity_key='core.daemon.mailSender.interval';
INSERT INTO core_datastore VALUES ('core.daemon.mailSender.interval', '86400');
DELETE FROM core_datastore WHERE entity_key='core.daemon.mailSender.onStartUp';
INSERT INTO core_datastore VALUES ('core.daemon.mailSender.onStartUp', 'true');
DELETE FROM core_datastore WHERE entity_key='core.daemon.threadLauncherDaemon.interval';
INSERT INTO core_datastore VALUES ('core.daemon.threadLauncherDaemon.interval', '86400');
DELETE FROM core_datastore WHERE entity_key='core.daemon.threadLauncherDaemon.onStartUp';
INSERT INTO core_datastore VALUES ('core.daemon.threadLauncherDaemon.onStartUp', 'true');
DELETE FROM core_datastore WHERE entity_key='core.frontOffice.defaultEditor';
INSERT INTO core_datastore VALUES ('core.frontOffice.defaultEditor', 'sceeditor');
DELETE FROM core_datastore WHERE entity_key='core.plugins.status.core_extensions.installed';
INSERT INTO core_datastore VALUES ('core.plugins.status.core_extensions.installed', 'true');
DELETE FROM core_datastore WHERE entity_key='core.plugins.status.junitplugin.installed';
INSERT INTO core_datastore VALUES ('core.plugins.status.junitplugin.installed', 'false');
DELETE FROM core_datastore WHERE entity_key='core.plugins.status.lucene.installed';
INSERT INTO core_datastore VALUES ('core.plugins.status.lucene.installed', 'true');
DELETE FROM core_datastore WHERE entity_key='core.startup.time';
INSERT INTO core_datastore VALUES ('core.startup.time', '10 sept. 2025 à 14:35:07');
DELETE FROM core_datastore WHERE entity_key='core.templates.currentCommonsInclude';
INSERT INTO core_datastore VALUES ('core.templates.currentCommonsInclude', 'Bootstrap5Tabler');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.admin_home_url';
INSERT INTO core_datastore VALUES ('portal.site.site_property.admin_home_url', 'jsp/admin/AdminMenu.jsp');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.avatar_default';
INSERT INTO core_datastore VALUES ('portal.site.site_property.avatar_default', 'themes/admin/shared/images/unknown.svg');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.bo.showXs.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.bo.showXs.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.bo.showXsWarning.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.bo.showXsWarning.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.email';
INSERT INTO core_datastore VALUES ('portal.site.site_property.email', '<webmaster email>');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.home_url';
INSERT INTO core_datastore VALUES ('portal.site.site_property.home_url', 'jsp/site/Portal.jsp');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.back_images';
INSERT INTO core_datastore VALUES ('portal.site.site_property.back_images', '');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.darkmode.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.darkmode.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.fluid.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.fluid.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.login.cover.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.login.cover.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.login.cover.contain.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.login.cover.contain.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.login.image';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.login.image', '');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.menu.condensed.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.menu.condensed.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.menu.home.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.menu.home.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.menu.sticky.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.menu.sticky.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.menu.transparent.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.menu.transparent.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.menu.vertical.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.menu.vertical.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.readmode.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.readmode.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.menu.boxed.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.menu.boxed.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.user.menumode.show.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.user.menumode.show.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.user.darkmode.show.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.user.darkmode.show.checkbox', '0');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.layout.user.readmode.show.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.layout.user.readmode.show.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.show_site_name.checkbox';
INSERT INTO core_datastore VALUES ('portal.site.site_property.show_site_name.checkbox', '1');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.locale.default';
INSERT INTO core_datastore VALUES ('portal.site.site_property.locale.default', 'fr');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.logo_svg.textblock';
INSERT INTO core_datastore VALUES ('portal.site.site_property.logo_svg.textblock', '<svg class="navbar-brand-image" width="60" height="24" viewBox="0 0 613 150.95206" width="613" height="150.95206" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">  <path d="m 232.2,13.8 -5.3,13.7 -7.7,3.2 -7.7,3.1 v 19.7 l 7.7,0.3 7.7,0.3 0.3,35.2 c 0.3,33.6 0.4,35.4 2.5,40.7 4.5,11 12.2,17 25.1,19.2 11.1,1.9 32.7,-1.2 38.6,-5.5 1.8,-1.3 1.7,-1.8 -1.9,-12.3 -2.1,-6 -4.1,-11.3 -4.5,-11.7 -0.4,-0.5 -2.7,0.1 -5.1,1.4 -5.1,2.6 -14.2,3.1 -18.1,1 -5.1,-2.7 -5.3,-4 -5.3,-37.5 V 53.5 L 271,53 283.5,52.5 v -22 L 271,30 258.5,29.5 258.2,14.7 257.9,0 H 237.5 Z M 258,42 V 54 H 233 V 30 h 25 z M 0,75 v 74 l 43.3,-0.2 43.2,-0.3 v -26 L 59.3,122.2 32,122 V 1 H 0 Z" />  <path fill="#3c67ff" d="M 284,16.5 V 29 h 25 V 4 h -25 z" />  <path fill="#ff442a" d="m 258.47,40.929 v 12.5 h 25 v -25 h -25 z" />  <path d="m 338.1,28.5 c -20.4,4.6 -34.6,18.9 -39.8,40.1 -2.4,9.8 -2.4,31.4 0,41.7 3.8,16.3 12.8,28.7 25.1,34.7 16.5,8.1 45,7.9 61.9,-0.4 9.1,-4.4 11.1,-6 10.3,-8.2 -0.3,-0.9 -3.4,-6.1 -6.8,-11.5 l -6.1,-9.8 -3,2.5 c -7,5.9 -17.4,9 -27.3,8.1 -10.7,-1 -17.4,-5 -21.5,-12.9 -1.9,-3.6 -4,-14.3 -3.1,-15.3 0.3,-0.3 16.2,-0.5 35.4,-0.5 32.3,0 34.9,-0.1 35.6,-1.8 0.4,-0.9 0.7,-8.5 0.7,-16.7 0,-13.1 -0.3,-15.9 -2.3,-21.7 -4.5,-13 -13.8,-22.3 -26.7,-26.9 -7.9,-2.7 -23.6,-3.4 -32.4,-1.4 z m 19.4,23.6 c 7.7,2.2 12.5,9.7 12.5,19.6 V 76 h -21 c -23.8,0 -22.3,0.6 -19.6,-8.4 3.8,-12.4 15.6,-19 28.1,-15.5 z m 93.9,-23.7 c -19.8,4.5 -33.7,18.9 -39.1,40.2 -2.4,9.5 -2.4,35.1 0,44.8 6.6,26.5 24.2,38.7 53.7,37.3 6.6,-0.3 13,-1.3 17.2,-2.6 7,-2.3 17.5,-9.2 20.4,-13.6 l 1.7,-2.6 -9.9,-9.3 -9.9,-9.3 -4.1,4.3 c -5.2,5.3 -12.8,8 -19.7,7 -13.5,-2 -19.4,-15 -18.5,-40.7 0.5,-13.2 2.3,-19.6 7.1,-24.7 7.6,-8.1 22.2,-7.7 30.8,0.9 l 4,4 5.7,-5 c 3.1,-2.7 7.9,-7.2 10.6,-10 l 5,-5.1 -2.9,-3 c -4.4,-4.6 -11.8,-9 -18.8,-11.2 -8.2,-2.6 -25,-3.3 -33.3,-1.4 z m 100.1,0.3 C 536,32 523.9,41.4 517,55.4 c -5.8,11.8 -7.3,20 -6.7,37.6 0.5,15.4 2.2,23.2 7.4,33.4 3.2,6.3 11.6,14.7 17.9,17.9 10,5.1 15.7,6.2 31.9,6.1 16.8,0 23.9,-1.4 33.7,-6.6 9.9,-5.3 9.9,-4.9 2.1,-17.5 l -6.8,-11 -5.5,3.8 c -11.8,8.2 -28.1,9 -39.3,1.9 -5.3,-3.3 -9.3,-10.6 -10.3,-18.8 L 540.7,97 h 71.1 l 0.6,-2.3 c 0.3,-1.2 0.6,-8.6 0.6,-16.4 0,-20.4 -3.4,-30.1 -13.9,-39.6 -11.5,-10.3 -29.1,-14 -47.6,-10 z m 23.8,25 c 4.6,2.6 7.7,9.3 7.7,16.5 V 76 h -41 v -3.3 c 0,-8 7.5,-17.7 15.7,-20.4 4.9,-1.6 13.5,-0.9 17.6,1.4 z M 94.7,29.6 c -1.2,1.2 -0.8,86.4 0.4,93 2.4,12.9 9.3,21.9 20,25.9 4.2,1.6 7.9,2 16.4,2 13.4,0 19.3,-1.8 27.1,-8.1 l 5.4,-4.4 2.5,5.5 2.4,5.5 H 195 V 90 c 0,-32.5 0.1,-59.3 0.3,-59.8 0.1,-0.4 -6.9,-0.8 -15.5,-1 L 164,28.9 v 82.9 l -3.2,4.8 c -8.3,12.2 -25.5,12.9 -32.2,1.4 -2,-3.3 -2.1,-5.4 -2.6,-46 l -0.5,-42.5 -15.1,-0.3 c -8.2,-0.1 -15.3,0.1 -15.7,0.4 z" /></svg><!--  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 553.71 146" width="60" height="24" ><title>logo-paris</title><path fill="#002542" d="M224.11 27.8h-34.2v90.4h20.7V89.8h13.6c17.8 0 31.6-13.8 31.6-31s-13.81-31-31.7-31zm0 42.6h-13.6V47.2h13.6c6.4 0 11 5 11 11.6s-4.6 11.6-11 11.6zM444.91 27.8h20.7v90.4h-20.7zM423.11 58.8a30.9 30.9 0 0 0-31-31H356v90.4h20.7V89.8h10.5l16.3 28.4h22.2l-19-32.7c10.01-4.7 16.41-15.6 16.41-26.7zm-30.9 13h-15.5V47.2h15.5c5.7 0 10.3 5.3 10.3 12.3s-4.6 12.3-10.3 12.3zM286.21 27.8l-30.7 90.4h22.6l5-15.9a66.61 66.61 0 0 0 32.4 0l5.1 15.9h22.6l-30.7-90.4zm13.1 58.4a41.83 41.83 0 0 1-10.7-1.3l10.7-33.5L310 84.9a46.79 46.79 0 0 1-10.69 1.3zM528.11 65.3c-14-4.2-19.7-6.6-19.7-12.3 0-4.3 4.1-6.8 9.7-6.8 9 0 12.7 4.8 15.8 9.3l17.2-9.1c-2.9-5.7-11.3-20.4-33-20.4-15.3 0-30.3 9.7-30.3 27.5 0 21.3 20.3 25.3 26.6 27.5s18.7 3.8 18.7 11.5c0 5.4-5.6 7.4-12.9 7.4-8.1 0-14.6-4.5-18.6-11.4L484 97.7c1.3 3.8 11.6 22.3 36.1 22.3 19.3 0 33.6-10.2 33.6-27.8.01-13.9-7.59-21.6-25.59-26.9zM157.51 86.7c-.6 0-1 .5-1.7 1.9-14.4 31.6-41 46.7-69.1 46.9-56.1.4-69.3-45.7-69.6-47l28.6 5.3c.1.3 11.1 25.5 40 25.5 30.6 0 51.8-30.5 51.8-62 0-28.4-12-44.6-29.3-57.3l-77.9 36a.79.79 0 0 0 .2 1.5c43.1 10 50.5 41 48.4 58.6-.3 2.6 1.4 2.2 3.1-2.7 5.9-17.5 1.7-42.9-21.7-57.2 0 0 43.3-21.7 43.3-21.6 5.2 4 22.2 15.5 22.2 42.8s-15.8 52.1-40.1 52.1c-24.1 0-32.5-24.6-32.7-25L1.51 73.3A1.23 1.23 0 0 0 0 74.6C4.5 113.9 35.9 146 81.5 146c37.8 0 63.5-20.8 74.4-50.1 2.51-6.8 2.41-9.2 1.61-9.2z"/></svg> -->');
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.logo_url';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.meta.author';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.meta.copyright';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.meta.description';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.meta.keywords';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.name';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.noreply_email';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.popup_credits.textblock';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.popup_legal_info.copyright.textblock';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.popup_legal_info.privacy.textblock';
DELETE FROM core_datastore WHERE entity_key='portal.site.site_property.portlet.title.maxlength';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.accessibilityLabel';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.accessibilityURL';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.account';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.auth';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.cguURL';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.cguURLLabel';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.clientId';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.contactURL';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.contactURLLabel';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.cookieURL';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.dataURL';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.dataURLLabel';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.legalURL';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.legalURLLabel';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.search';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.wikiURL';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.Url.wikiURLLabel';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.credits';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.fixed.checkbox'; 
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.internal.checkbox'; 
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.image.positionx';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.image.positiony';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.showSiteImgEverywhere.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.shown.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.title.bgcolor';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.title.color';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.banner.title.padding';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerBrowserWarning.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerForm.showBannerImg.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerForm.showFormImg.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerForm.showFormTitle.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerMessage.CloseButton.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerMessage.Duration';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerMessage.Position';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerMessage.Title';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerMessage.Type';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.bannerMessage.htmlblock';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.config.datepicker.textblock';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.config.editor.textblock';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.config.locales'; 
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.layout.colors.dark.textblock';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.layout.colors.light.textblock';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.layout.customstyles.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.layout.dir.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.layout.theme.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.layout.footerSocial.checkbox'; 
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.layout.type.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.forms.showResponseFormWarning.checkbox'; 
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.forms.labelInfoResponse'; 
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.link.showTargetIcon.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.menu.fixedMenu.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.menu.gototop.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.menu.hasDefaultMenu.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.menu.sidebarMenu.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.menu.siteMapMenu.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.menu.skipLinkMainId';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.menu.skipLinkMenu.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.menu.userthemeswitch.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.robotIndex.checkbox';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.xss.xssChars';
DELETE FROM core_datastore WHERE entity_key='portal.theme.site_property.xss.xssMsg';
DELETE FROM core_datastore WHERE entity_key='theme.globalThemeCode';
DELETE FROM core_datastore WHERE entity_key='theme.globalThemeVersion';
INSERT INTO core_datastore VALUES ('portal.site.site_property.logo_url', '');
INSERT INTO core_datastore VALUES ('portal.site.site_property.meta.author', '<author>');
INSERT INTO core_datastore VALUES ('portal.site.site_property.meta.copyright', '<copyright>');
INSERT INTO core_datastore VALUES ('portal.site.site_property.meta.description', '<description>');
INSERT INTO core_datastore VALUES ('portal.site.site_property.meta.keywords', '<keywords>');
INSERT INTO core_datastore VALUES ('portal.site.site_property.name', 'LUTECE');
INSERT INTO core_datastore VALUES ('portal.site.site_property.noreply_email', 'no-reply@mydomain.com');
INSERT INTO core_datastore VALUES ('portal.site.site_property.popup_credits.textblock', '<credits text>');
INSERT INTO core_datastore VALUES ('portal.site.site_property.popup_legal_info.copyright.textblock', '<copyright text>');
INSERT INTO core_datastore VALUES ('portal.site.site_property.popup_legal_info.privacy.textblock', '<privacy text>');
INSERT INTO core_datastore VALUES ('portal.site.site_property.portlet.title.maxlength', '75');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.accessibilityLabel', 'Acccesibilité partiellement conforme');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.accessibilityURL', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.account', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.auth', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.cguURL', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.cguURLLabel', 'Condition générales d\'utilisation');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.clientId', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.contactURL', 'jsp/site/Portal.jsp?page=contact&view=viewContactPage&id_contact_list=1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.contactURLLabel', 'Contact');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.cookieURL', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.dataURL', 'jsp/site/PopupCredits.jsp');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.dataURLLabel', 'Politique de gestion des données à caractère personnel');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.legalURL', 'jsp/site/PopupLegalInfo.jsp');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.legalURLLabel', 'Mentions légales');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.search', 'jsp/site/Portal.jsp?page=search');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.wikiURL', 'https://lutece.paris.fr/support');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.Url.wikiURLLabel', 'Wiki');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner', 'images/banner.jpg');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.credits', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.fixed.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.internal.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.image.positionx', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.image.positiony', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.showSiteImgEverywhere.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.shown.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.title.bgcolor', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.title.color', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.banner.title.padding', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerBrowserWarning.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerForm.showBannerImg.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerForm.showFormImg.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerForm.showFormTitle.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerMessage.CloseButton.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerMessage.Duration', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerMessage.Position', 'top:1rem;right:1rem;');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerMessage.Title', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerMessage.Type', 'info');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.bannerMessage.htmlblock', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.config.datepicker.textblock', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.config.editor.textblock', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.config.locales', 'fr');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.layout.colors.dark.textblock', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.layout.colors.light.textblock', '');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.layout.customstyles.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.layout.dir.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.layout.theme.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.layout.type.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.layout.footerSocial.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.forms.showResponseFormWarning.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.link.showTargetIcon.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.fixedMenu.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.gototop.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.hasDefaultMenu.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.sidebarMenu.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.sidebarMenu.sidebarCol.number', '3');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.sidebarMenuCollapse.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.siteMapMenu.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.search.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.skipLinkMainId', 'main');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.skipLinkMenu.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.menu.userthemeswitch.checkbox', '1');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.robotIndex.checkbox', '0');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.xss.xssChars', '<>#"&');
INSERT INTO core_datastore VALUES ('portal.theme.site_property.xss.xssMsg', 'Les caract\\u00e8res &#60; &#62; &#35; et &#34;  &amp; sont interdits dans le contenu de votre message.');
INSERT INTO core_datastore VALUES ('theme.globalThemeCode', 'lutece');
INSERT INTO core_datastore VALUES ('theme.globalThemeVersion', '1.0');

DELETE FROM  core_admin_right WHERE id_right='THEME_MANAGEMENT';
INSERT INTO core_admin_right VALUES ('CORE_THEME_MANAGEMENT','portal.theme.adminFeature.theme_management.name',0,'jsp/admin/theme/ManageThemes.jsp','portal.theme.adminFeature.theme_management.description',1,'','STYLE','ti ti-palette', NULL, 1, 0);

DELETE FROM core_admin_security_header WHERE id_security_header=3;
INSERT INTO core_admin_security_header VALUES (3, 'Content-Security-Policy', 'default-src \'self\'; script-src \'self\' \'unsafe-inline\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data: blob:; connect-src \'self\' blob:; object-src \'none\'; font-src \'self\' data:;form-action \'self\'; frame-ancestors \'self\'; upgrade-insecure-requests', 'The HTTP Content-Security-Policy response header allows website administrators to control resources the user agent is allowed to load for a given page. With a few exceptions, policies mostly involve specifying server origins and script endpoints. This helps guard against cross-site scripting attacks (Cross-site_scripting). The directives recommended by OWASP are ""default-src \'self\'; form-action \'self\'; object-src \'none\'; frame-ancestors \'none\'; upgrade-insecure-requests; block-all-mixed-content"". For Lutece, the values of the directives of this policy have been defined as close as possible to this recommendation. However, hey are different because they take into account of the specificities of Lutece existing code and more specifically the constraints of tiny mce library that needs specific configuration for this header.', 'page', 'all', 1);

