-- liquibase formatted sql
-- changeset core:update_db_lutece_core-7.0.16-7.0.17.sql
-- preconditions onFail:MARK_RAN onError:WARN
--
-- Table structure for table core_admin_security_header
--
DROP TABLE IF EXISTS core_admin_security_header;
CREATE TABLE core_admin_security_header (
  id_security_header SMALLINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(60) NOT NULL,
  value VARCHAR(1024) NOT NULL,
  description VARCHAR(1024) DEFAULT NULL,
  type VARCHAR(10) NOT NULL,
  page_category VARCHAR(25) DEFAULT NULL,
  is_active SMALLINT DEFAULT 0,
  PRIMARY KEY  (id_security_header)
);

INSERT INTO core_admin_right VALUES ('CORE_SECURITY_HEADER_MANAGEMENT', 'portal.system.adminFeature.security_header_management.name', 0, 'jsp/admin/system/ManageSecurityHeaders.jsp', 'portal.system.adminFeature.security_header_management.description', 1, '', 'SYSTEM', 'ti ti-box-align-top', NULL, 12, 0);

INSERT INTO core_user_right VALUES ('CORE_SECURITY_HEADER_MANAGEMENT',1);

INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Strict-Transport-Security', 'max-age=31536000; includeSubDomains','The HTTP Strict-Transport-Security response header (often abbreviated as HSTS) informs browsers that the site should only be accessed using HTTPS, and that any future attempts to access it using HTTP should automatically be converted to HTTPS. The value recommended by OWASP for this header is ''max-age=31536000; includeSubDomains'' and this is the value retained for Lutece. This setting means that the browser should remember that this site and all of his subdomains are only to be accessed using HTTPS for 31536000 seconds (1 year).', 'page', 'all', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('X-Content-Type-Options', 'nosniff', 'The X-Content-Type-Options response HTTP header is a marker used by the server to indicate that the MIME types advertised in the Content-Type headers should be followed and not be changed. The header allows you to avoid MIME type sniffing by saying that the MIME types are deliberately configured. The value recommended by OWASP for this header is ''nosniff'' and this is the value retained for Lutece. ''nosniff'' value will prevent the browser from MIME-sniffing a response away from the declared content-type.', 'page', 'all', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Content-Security-Policy', 'default-src ''self''; script-src ''self'' ''unsafe-inline''; style-src ''self'' ''unsafe-inline''; img-src ''self'' data: blob:; connect-src ''self'' blob:; object-src ''none''; form-action ''self''; frame-ancestors ''self''; upgrade-insecure-requests','The HTTP Content-Security-Policy response header allows website administrators to control resources the user agent is allowed to load for a given page. With a few exceptions, policies mostly involve specifying server origins and script endpoints. This helps guard against cross-site scripting attacks (Cross-site_scripting). The directives recommended by OWASP are ""default-src ''self''; form-action ''self''; object-src ''none''; frame-ancestors ''none''; upgrade-insecure-requests; block-all-mixed-content"". For Lutece, the values of the directives of this policy have been defined as close as possible to this recommendation. However, hey are different because they take into account of the specificities of Lutece existing code and more specifically the constraints of tiny mce library that needs specific configuration for this header.', 'page', 'all', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('X-Permitted-Cross-Domain-Policies', 'none', 'This header is used to limit which data external resources, such as Adobe Flash and PDF documents, can access on the domain. The value recommended by OWASP for this header is ''none'' and this is the value retained for Lutece. It means that o policy files are allowed anywhere on the target server, including this master policy file.','page','all',1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Referrer-Policy', 'no-referrer','The Referrer-Policy HTTP header controls how much referrer information (sent with the Referer header) should be included with requests. Aside from the HTTP header, you can set this policy in HTML. The value recommended by OWASP for this header is ''no-referrer'' and this is the value retained for Lutece. The Referer header included with requests will be omitted entirely. No referrer information is sent along with requests.','page','all',1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Cross-Origin-Embedder-Policy', 'require-corp', 'The HTTP Cross-Origin-Embedder-Policy (COEP) response header configures embedding cross-origin resources into the document. The value recommended by OWASP for this header is ''require-corp'' and this is the value retained for Lutece. It means that a document can only load resources from the same origin (i.e. protocol/scheme + host + port), or resources explicitly marked as loadable from another origin.','page','all',1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Cross-Origin-Opener-Policy', 'same-origin', 'The HTTP Cross-Origin-Opener-Policy (COOP) response header allows you to ensure a top-level document does not share a browsing context group with cross-origin documents. The value recommended by OWASP for this header is ''same-origin'' and this is the value retained for Lutece. This value permits to isolates the browsing context exclusively to same-origin documents. Cross-origin documents are not loaded in the same browsing context.', 'page','all', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Cross-Origin-Resource-Policy', 'same-site', 'The HTTP Cross-Origin-Resource-Policy response header conveys a desire that the browser blocks no-cors cross-origin/cross-site requests to the given resource. The value recommended by OWASP for this header is ''same-origin'' and the value retained for Lutece is ''same-site'' which means that only requests from the same Site can read the resource. It is less restrictive than ''same-origin'' in order to allow Lutece sub-domains to access to resources.', 'page', 'all', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Cache-Control', 'max-age=0, must-revalidate, no-cache, no-store, private', 'The Cache-Control HTTP header field holds directives (instructions) — in both requests and responses — that control caching in browsers and shared caches (e.g. Proxies, CDNs). The value recommended by OWASP for this header is ''no-store, max-age=0''. For Lutece, the directives retained are ''max-age=0, must-revalidate, no-cache, no-store, private'' and are applied to administration front office/back office pages with authentication in order to prevent caching of any information. Theoretically, OWASP recommended directives should be suficient but in practice some browsers may continue to use the cache or don''t support no-store directive. So, for Lutece, more directives have been added to prevent caching. For instance, the login page of gmail uses the following directives : no-cache, no-store, max-age=0, must-revalidate', 'page', 'auth_admin_BO', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Cache-Control', 'max-age=0, must-revalidate, no-cache, no-store, private', 'The Cache-Control HTTP header field holds directives (instructions) — in both requests and responses — that control caching in browsers and shared caches (e.g. Proxies, CDNs). The value recommended by OWASP for this header is ''no-store, max-age=0''. For Lutece, the directives retained are ''max-age=0, must-revalidate, no-cache, no-store, private'' and are applied to administration front office/back office pages with authentication in order to prevent caching of any information. Theoretically, OWASP recommended directives should be suficient but in practice some browsers may continue to use the cache or don''t support no-store directive. So, for Lutece, more directives have been added to prevent caching. For instance, the login page of gmail uses the following directives : no-cache, no-store, max-age=0, must-revalidate', 'page', 'auth_admin_FO', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Clear-Site-Data', '"cache","cookies","storage"', 'The Clear-Site-Data header clears browsing data (cookies, storage, cache) associated with the requesting website. It allows web developers to have more control over the data stored by a client browser for their origins. This header is useful for example, during a logout process, in order to ensure that all stored content on the client side like cookies, storage and cache are removed. The value recommended by OWASP for this header is ''"cache","cookies","storage"'' and this is the value retained for Lutece. It is added to the front office/back office logout pages of Lutece.', 'page', 'logout_BO', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Clear-Site-Data', '"cache","cookies","storage"', 'The Clear-Site-Data header clears browsing data (cookies, storage, cache) associated with the requesting website. It allows web developers to have more control over the data stored by a client browser for their origins. This header is useful for example, during a logout process, in order to ensure that all stored content on the client side like cookies, storage and cache are removed. The value recommended by OWASP for this header is ''"cache","cookies","storage"'' and this is the value retained for Lutece. It is added to the front office/back office logout pages of Lutece.', 'page', 'logout_FO', 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Strict-Transport-Security', 'max-age=31536000; includeSubDomains', 'The HTTP Content-Security-Policy response header allows website administrators to control resources the user agent is allowed to load for a given page. With a few exceptions, policies mostly involve specifying server origins and script endpoints. This helps guard against cross-site scripting attacks (Cross-site_scripting). The value recommended by OWASP for this header when used as a response of an API call is ''frame-ancestors ''none'''' and this is the value retained for Lutece. It prevents any domain from framing the response returned by the API call.', 'rest_api', NULL, 1);
INSERT INTO core_admin_security_header (name, value, description, type, page_category, is_active) VALUES ('Content-Security-Policy', 'frame-ancestors ''none''', 'The HTTP Strict-Transport-Security response header (often abbreviated as HSTS) informs browsers that the site should only be accessed using HTTPS, and that any future attempts to access it using HTTP should automatically be converted to HTTPS. The value recommended by OWASP for this header when used as a response of an API call is ''max-age=31536000; includeSubDomains'' and this is the value retained for Lutece. This setting means that the browser should remember that this site and all of his subdomains are only to be accessed using HTTPS for 31536000 seconds (1 year).', 'rest_api', NULL, 1);
